---
country: victoria
iso3: VIC
scenario_start_time: 130
times:
  start_time: 15.
  end_time: 365.

importation:
  active: True
  times: [70., 71., 86., 100., 107]
  cases: [1, 1, 45, 4, 1.1341]
  self_isolation_effect: .434371
  enforced_isolation_effect: .9858

infectious_seed: 0

contact_rate: 0.024
non_sympt_infect_multiplier: .464939

young_reduced_susceptibility: .4484674
prop_isolated_among_symptomatic: .8035
npi_effectiveness:
  other_locations: .9697829

mixing:
  other_locations:
    times:
      [
        72,
        73,
        74,
        75,
        76,
        77,
        78,
        79,
        80,
        81,
        82,
        83,
        84,
        85,
        86,
        87,
        88,
        89,
        90,
        91,
        92,
        93,
      ]
    values:
      [
        1.,
        .95,
        .89,
        .81,
        .79,
        .66,
        .53,
        .50,
        .49,
        .46,
        .42,
        .33,
        .25,
        .20,
        .20,
        .18,
        .18,
        .18,
        .18,
        .15,
        .15,
        .14,
      ]
  work:
    times:
      - 78.
      - 79.
      - 81.
      - 82.
      - 84.
      - 85.
      - 86.
      - 87.
      - 91.
      - 92.
    values:
      - 1.
      - 0.95
      - 0.95
      - 0.9
      - 0.9
      - 0.7
      - 0.7
      - 0.5
      - 0.5
      - 0.25
  school:
    times:
      - 84.
      - 85.
    values:
      - 1.
      - 0.
