---
# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 50
country: null
iso3: null

start_time: 0.
end_time: 100.
time_step: 1

contact_rate: 0.3
recovery_rate: 1.0
