---
# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 2020.0

country: null
iso3: null

start_time: 1900.
end_time: 2035.
time_step: 1.

# beta: 4.55

gamma: 0.2 
universal_death_rate: 0.0142
universal_death_rateX: 0.0142

tau: 1.

kappa: 3.6525 # (1.e-2 * 365.25)
nu: 0.002008875 # (5.5e-6 * 365.25)
epsilon: 0.401775 #(1.1e-3 * 365.25)


rr_reinfection_once_recovered: 0.05  # FIXME: seems very low. Where does it come from?



cdr: {}

scenarios: {}
