---
# # When to introduce the scenario interventions taking off from the baseline
# scenario_start_time: 50

# Parameters used to build a general model of DS-TB to understand rise in DR in Philippines
country: philippines
iso3: PHL
population_size: 106000000


start_time: 1900.
beta: 5.1

infect_death: .054

detection_rate: 0.45 # solve using CDR value and equation # data obtained for Philippines # FIXME: not used and not needed

TSR: .85 # data reported in WHO

relative_TSR_MDR: .67
relative_TSR_H: .5   # FIXME: Are we saying the TSR of INH-resistant patients is worse than that of MDR-TB?
relative_TSR_R: .67


prop_of_failures_developing_inh_R: 11 # FIXME: proportion
prop_of_failures_developing_rif_R: 0.8
