---
# # When to introduce the scenario interventions taking off from the baseline
# scenario_start_time: 50

# Parameters used to build a general model of DS-TB to understand rise in DR in Philippines
country: philippines
iso3: PHL

start_time: 1900.
beta: 5.1

infect_death: .054

detection_rate: 0.45 # solve using CDR value and equation # data obtained for Philippines

TSR: .85 # data reported in WHO

relative_TSR_MDR: .67
relative_TSR_H: .5
relative_TSR_R: .67

cdr:
  1950: 0.
  1970: 0.02
  2015: .05

prop_of_failures_developing_inh_R: 11
prop_of_failures_developing_rif_R: 0.8
