---
# # When to introduce the scenario interventions taking off from the baseline
# scenario_start_time: 50

# Parameters used to build a general model of DS-TB to understand rise in DR in Philippines
country: philippines
iso3: PHL

start_time: 1900.
beta: 4.5

TSR: .70 # data reported in WHO

cdr:
  1950: 0.
  2015: .50

prop_of_failures_developing_inh_R: 0.065
prop_of_failures_developing_rif_R: 0.015
