---
# # When to introduce the scenario interventions taking off from the baseline
# scenario_start_time: 50

# Parameters used to build a general model of DS-TB to understand rise in DR in Philippines
country: philippines
iso3: PHL
population_size: 106000000


start_time: 1900.
beta: 5.1

tsr_final_level: .85 # data reported in WHO

relative_TSR_MDR: .6
relative_TSR_H: .65
relative_TSR_R: .75
