# Environment variables are:
# - PGDATABASE
# - PGPASSWORD
# - PGUSER
# - ADMIN_USERNAME
# - ADMIN_PASSWORD
version: "3.2"

services:
  db:
    networks:
      - network
    image: postgres
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_PASSWORD: $PGPASSWORD
      POSTGRES_USER: $PGUSER
    volumes:
      - postgres-data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  web:
    networks:
      - network
    image: concourse/concourse
    command: web
    depends_on: [db]
    ports: ["8080:8080"]
    volumes: ["./keys/web:/concourse-keys"]
    environment:
      CONCOURSE_EXTERNAL_URL: http://52.62.208.189/
      CONCOURSE_POSTGRES_HOST: db
      CONCOURSE_POSTGRES_USER: $PGUSER
      CONCOURSE_POSTGRES_PASSWORD: $PGPASSWORD
      CONCOURSE_POSTGRES_DATABASE: $PGDATABASE
      CONCOURSE_ADD_LOCAL_USER: $ADMIN_USERNAME:$ADMIN_PASSWORD
      CONCOURSE_MAIN_TEAM_LOCAL_USER: $ADMIN_USERNAME
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

volumes:
  postgres-data:

networks:
  network:
    driver: overlay
    attachable: true
