resources:
  - name: autumn-repo
    type: git
    source:
      uri: https://github.com/monash-emu/AuTuMN.git
      branch: concourse

jobs:
  - name: job-test
    public: true
    plan:
      - get: autumn-repo
      - task: setup-env
        file: autumn-repo/scripts/concourse/tasks/virtualenv/task.yml
