resources:
  - name: autumn-repo
    type: git
    source:
      uri: https://github.com/monash-emu/AuTuMN.git
      branch: concourse

jobs:
  - name: test-job
    public: true
    plan:
      - get: autumn-repo
      - task: aws-status
        file: autumn-repo/scripts/concourse/tasks/aws-status/task.yml
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python }
          inputs:
            - name: autumn-repo
          params:
            AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
            AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
          run:
            path: autumn-repo/scripts/aws/run.sh status
