resources:
  - name: autumn-repo
    type: git
    source:
      uri: https://github.com/monash-emu/AuTuMN.git
      branch: concourse

jobs:
  - name: job-test
    public: true
    plan:
      - get: autumn-repo
      - task: view-dir
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: ubuntu }
          run:
            path: pwd
      - task: hello-world
        file: tasks/hello.yml
