resources:
  - name: autumn-repo
    type: git
    source:
      uri: https://github.com/monash-emu/AuTuMN.git
      branch: concourse

jobs:
  - name: calibrate
    plan:
      - get: autumn-repo
      - task: run-calibration
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: { repository: python }
          inputs:
            - name: autumn-repo
          params:
            AWS_SECRET_ACCESS_KEY: ((AWS_SECRET_ACCESS_KEY))
            AWS_ACCESS_KEY_ID: ((AWS_ACCESS_KEY_ID))
            AWS_SSH_KEY_1: ((AWS_SSH_KEY_1))
            AWS_SSH_KEY_2: ((AWS_SSH_KEY_2))
          run:
            path: autumn-repo/scripts/concourse/tasks/calibrate.sh
            args: ["((model))"]
