---
# Base COVID parameters

# When to introduce the scenario interventions taking off from the baseline
scenario_start_time: 85

# Country to extract Prem mixing matrix from
country: null

# Country to extract stratified population data from - should eventually use only one of country or iso3
iso3: null

# Running time-related - for COVID-19 model, all times are assumed to be in days and reference time is 1st Jan 2020
times:
  start_time: 40.
  end_time: 350.
  time_step: 1

# Parameters used to build a general model of COVID-19 disease for application to Australia or internationally
# MODEL STRUCTURE PARAMETERS

importation:
  active: False
  times: []
  cases: []
  # parameters to define the effect (infectiousness adjustment) of self-isolation and enforced isolation
  self_isolation_effect: .67
  enforced_isolation_effect: 1.

# Mean time (?) spent in each compartment
compartment_periods:
  hospital_early: 5.
  hospital_late: 8.
  icu_early: 5.
  icu_late: 10.

# Mean time (?) spent in each compartment, defined via proprotions
compartment_periods_calculated:
  total_infectious:
    total_period: 7.
    proportions:
      infectious: 0.333
      late: 0.667

  incubation:
    total_period: 5.
    proportions:
      exposed: 0.5
      presympt: 0.5

# AGE-STRATIFIED PARAMETERS

# Infectiousness progression adjustments - in ten year brackets that need to be adapted to model strata later
# Extracted by WebPlotDigitizer from the LSHTM's "Age-dependent effects in the ..." Fig 2b, upper-left panel
symptomatic_props:
  - 0.396
  - 0.252
  - 0.367
  - 0.408
  - 0.476
  - 0.572
  - 0.710
  - 0.745

# Proportion of symptomatic persons that are hospitalised - Verity et al.
hospital_props:
  - 0.001
  - 0.003
  - 0.012
  - 0.032
  - 0.049
  - 0.102
  - 0.166
  - 0.243
  - 0.273
hospital_inflate: False

# Proportion of those hospitalised that are admitted to ICU - consistent with LSHTM's LMIC estimates parameters
icu_prop: 0.3

# Infection fatality proportions - Verity et al.
infection_fatality_props:
  - 0.00002
  - 0.00006
  - 0.0003
  - 0.0008
  - 0.0015
  - 0.006
  - 0.022
  - 0.051
  - 0.093

# Reduced susceptibility in children - assumed, but informed by Iceland NEJM paper
young_reduced_susceptibility: 0.5
reduced_susceptibility_agegroups: [0, 5, 10, 15]

# NON-AGE-STRATIFIED PARAMETERS

# Adjust the infectiousness of clinical strata - assumed
non_sympt_infect_multiplier: 0.5
hospital_non_icu_infect_multiplier: 0.2
icu_infect_multiplier: 0.2

# proportion of isolated cases among symptomatic
prop_isolated_among_symptomatic: 0.6

# Initial conditions
infectious_seed: 10

# Base model definition
contact_rate: 0.03 # Expected to be calibrated for each application
icu_mortality_prop: 0.5

# Compulsory parameter that is completely overwritten in stratification, rather than being modified
infect_death: 0.

# Compulsory parameter for all models, even though there are no population-wide deaths
universal_death_rate: 0.

# Parameters relating to adjusting the mixing matrix to reflect interventions
mixing: {}
npi_effectiveness: {}
