---
# Parameters used to build a general model of DS-TB

country: vietnam
iso3: VIT
population_size: 95000000

start_time: 1900.
beta: 5


infect_death: .08 # WHO data

detection_rate: 0.39 # solve using CDR value and equation # data obtained for vietnam # FIXME: not used and not needed

TSR: .90 # data reported in WHO

relative_TSR_MDR: .75
relative_TSR_H: .65 # FIXME: Are we saying the TSR of INH-resistant patients is worse than that of MDR-TB?
relative_TSR_R: .75


prop_of_failures_developing_inh_R: 5.5 # FIXME: Proportion
prop_of_failures_developing_rif_R: 0.027
