---
# Parameters used to build a general model of DS-TB

country: vietnam
iso3: VIT

start_time: 1900.
beta: 5


infect_death: .08 # WHO data

detection_rate: 0.39 # solve using CDR value and equation # data obtained for vietnam

TSR: .90 # data reported in WHO

relative_TSR_MDR: .75
relative_TSR_H: .65
relative_TSR_R: .75

cdr:
    1950.: 0.0
    1970.: 0.4
    2015.: .5



prop_of_failures_developing_inh_R: 5.5
prop_of_failures_developing_rif_R: 0.027
