---
# Parameters used to build a general model of DS-TB

country: vietnam
iso3: VIT
population_size: 95000000

start_time: 1900.
beta: 5

TSR: .90 # data reported in WHO

relative_TSR_MDR: .6
relative_TSR_H: .65
relative_TSR_R: .75
