---
platform: linux

image_resource:
  type: docker-image
  source: { repository: python }

inputs:
  - name: autumn-repo

outputs:
  - name: venv

run:
  path: autumn-repo/scripts/concourse/tasks/virtualenv/run.sh
